model:
  type: transformer
  transformer:
    model_name: all-MiniLM-L6-v2
    batch_size: 32
  tfidf:
    max_features: 15000
    min_df: 2
    max_df: 0.85

matching:
  min_score_threshold: 0.4
  batch_size: 100

logging:
  level: INFO
  format: '%(asctime)s - %(levelname)s - %(message)s'
  file: logs/screening.log

data:
  preprocessing:
    min_words: 10
    max_length: 1000
    remove_stopwords: true
